title: Grattis, Lena!
permalink: pretty
plugins:
  - jekyll-readme-index
  - jemoji
exclude:  
 - Gemfile
 - Gemfile.lock
 - LICENSE
defaults:
 - scope:
    path: README.md
   values: 
    layout: default
readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false    